tasks:
  - init: poetry self update && pyenv update && pyenv install 3.10.4 && pyenv global 3.10.4
    command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && sudo apt update && sudo apt dist-upgrade